test_task:
  container:
    image: openjdk:11-jdk-slim
  gradle_cache:
    folder: ~/.gradle
    fingerprint_script: cat build.gradle.kts gradle/libs.versions.toml
    populate_script: ./gradlew dependencies
  test_script: ./gradlew test
