test_task:
  container:
    image: openjdk:11-jdk-slim
  gradle_cache:
    folder: ~/.gradle
    fingerprint_script: cat build.gradle.kts buildSrc/src/main/kotlin/Plugin.kt buildSrc/src/main/kotlin/Lib.kt
    populate_script: ./gradlew dependencies
  test_script: ./gradlew test
