name: shutdownserver
description: A server app using the shelf package and Docker.
version: 8.0.0

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  args: ^2.3.0
  dotenv: ^4.0.0
  ffi: ^2.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^1.2.2
  meta: ^1.0.0
  shelf: ^1.4.0
  shelf_plus: ^1.5.1
  shelf_router: ^1.1.0
  win32: ^4.1.1

dev_dependencies:
  build_runner: ^2.3.3
  http: ^0.13.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
