version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: openjdk:11-jdk-slim

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
    - checkout
    - run: chmod +x gradlew

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}
          - v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}
          - v2-dependencies-{{ checksum "build.gradle.kts" }}
          - v2-dependencies-

    - run: ./gradlew dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}

    # run tests!
    - run: ./gradlew test

    - store_test_results:
        path: build/test-results

  markdown_lint:
    docker:
      - image: 06kellyjac/markdownlint-cli:0.13.0-alpine
    steps:
      - checkout
      - run: markdownlint README.md


workflows:
  version: 2
  full_workflow:
    jobs:
      - markdown_lint
      - build
