name: Main

on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image: dart:2.19
    steps:
      - uses: actions/checkout@v3
      - name: Dart format check
        run: dart format --set-exit-if-changed --output=none lib test bin

  lint:
    runs-on: ubuntu-latest
    container:
      image: dart:2.19
    steps:
      - uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Code generation
        run: dart run build_runner build
      - name: Dart analyze
        run: dart analyze --fatal-infos
